// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: service_sleep_tracking.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SleepTracking_GetUserSleepLogs_FullMethodName = "/pb.SleepTracking/GetUserSleepLogs"
)

// SleepTrackingClient is the client API for SleepTracking service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SleepTrackingClient interface {
	GetUserSleepLogs(ctx context.Context, in *GetUserSleepLogsRequest, opts ...grpc.CallOption) (*GetUserSleepLogsResponse, error)
}

type sleepTrackingClient struct {
	cc grpc.ClientConnInterface
}

func NewSleepTrackingClient(cc grpc.ClientConnInterface) SleepTrackingClient {
	return &sleepTrackingClient{cc}
}

func (c *sleepTrackingClient) GetUserSleepLogs(ctx context.Context, in *GetUserSleepLogsRequest, opts ...grpc.CallOption) (*GetUserSleepLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserSleepLogsResponse)
	err := c.cc.Invoke(ctx, SleepTracking_GetUserSleepLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SleepTrackingServer is the server API for SleepTracking service.
// All implementations must embed UnimplementedSleepTrackingServer
// for forward compatibility.
type SleepTrackingServer interface {
	GetUserSleepLogs(context.Context, *GetUserSleepLogsRequest) (*GetUserSleepLogsResponse, error)
	mustEmbedUnimplementedSleepTrackingServer()
}

// UnimplementedSleepTrackingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSleepTrackingServer struct{}

func (UnimplementedSleepTrackingServer) GetUserSleepLogs(context.Context, *GetUserSleepLogsRequest) (*GetUserSleepLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserSleepLogs not implemented")
}
func (UnimplementedSleepTrackingServer) mustEmbedUnimplementedSleepTrackingServer() {}
func (UnimplementedSleepTrackingServer) testEmbeddedByValue()                       {}

// UnsafeSleepTrackingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SleepTrackingServer will
// result in compilation errors.
type UnsafeSleepTrackingServer interface {
	mustEmbedUnimplementedSleepTrackingServer()
}

func RegisterSleepTrackingServer(s grpc.ServiceRegistrar, srv SleepTrackingServer) {
	// If the following call pancis, it indicates UnimplementedSleepTrackingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SleepTracking_ServiceDesc, srv)
}

func _SleepTracking_GetUserSleepLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSleepLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SleepTrackingServer).GetUserSleepLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SleepTracking_GetUserSleepLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SleepTrackingServer).GetUserSleepLogs(ctx, req.(*GetUserSleepLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SleepTracking_ServiceDesc is the grpc.ServiceDesc for SleepTracking service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SleepTracking_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SleepTracking",
	HandlerType: (*SleepTrackingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserSleepLogs",
			Handler:    _SleepTracking_GetUserSleepLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_sleep_tracking.proto",
}
