// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateSleepLog(ctx context.Context, arg CreateSleepLogParams) (SleepLog, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSleepLogByID(ctx context.Context, arg DeleteSleepLogByIDParams) error
	GetSleepLogsByUserID(ctx context.Context, arg GetSleepLogsByUserIDParams) ([]SleepLog, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
}

var _ Querier = (*Queries)(nil)
