name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name : Install dependencies
        run: go mod download

      - name: Run tests
        run: make test